### ISSUE TITLE
Two of the nine components of stream is not migrated

### ISSUE THREAD

**Issue by areebrtc** [WtfJoke/rtc2git#152]
My stream has nine components. Every time the same components are not migrated. Although the migration says it is completed successfully, I can start contributing to the repo created.

However, I get following errors reportedly on screen. 

SEVERE: Status ERROR: org.eclipse.equinox.registry code=1 Plug-in com.ibm.team.filesystem.rcp.core was unable to load class com.ibm.team.filesystem.rcp.core.internal.resources.ResourceSharingManager. org.eclipse.core.runtime.CoreException: Plug-in com.ibm.team.filesystem.rcp.core was unable to load class com.ibm.team.filesystem.rcp.core.internal.resources.ResourceSharingManager. children=[Status ERROR: org.eclipse.equinox.registry code=1 Plug-in com.ibm.team.filesystem.rcp.core was unable to load class com.ibm.team.filesystem.rcp.core.internal.resources.ResourceSharingManager. org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter$TerminatingClassNotFoundException: An error occurred while automatically activating bundle com.ibm.team.filesystem.rcp.core (455).]
org.eclipse.core.runtime.CoreException: Plug-in com.ibm.team.filesystem.rcp.core was unable to load class com.ibm.team.filesystem.rcp.core.internal.resources.ResourceSharingManager.
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
        at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:904)
        at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
        at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
        at com.ibm.team.filesystem.client.internal.SharingManager.doGetInstance(SharingManager.java:139)
        at com.ibm.team.filesystem.client.internal.SharingManager.getInstance(SharingManager.java:157)
        at com.ibm.team.filesystem.cli.core.internal.ScmClientConfiguration.initializeDataArea(ScmClientConfiguration.java:530)
        at com.ibm.team.filesystem.cli.core.internal.ScmClientConfiguration.initialize(ScmClientConfiguration.java:208)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:583)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:370)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:130)
        at com.ibm.team.rtc.cli.infrastructure.internal.Application.start(Application.java:41)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1408)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1384)
Caused by: org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter$TerminatingClassNotFoundException: An error occurred while automatically activating bundle com.ibm.team.filesystem.rcp.core (455).
        at org.eclipse.core.runtime.internal.adaptor.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:121)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:453)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:393)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:469)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.eclipse.osgi.internal.loader.BundleLoader.loadClass(BundleLoader.java:338)

Some more errors are there related to above types. 

I followed following steps to run migration for RTC 5.0.2
1. created a new workspace for my stream.
2. replaced the baseline to initial. 
3. created a new clone to initial set baseline workspace. 
4. updated config.ini for WorkspaceName, Directory, ScmCommand, StreamToMigrate
5. executed migration

But after successfully migration, two of the components do not migrate.

**Comment by areebrtc** [comment]
I just noted a trend that after 15290 change set the above error is reported and once it is reported it is very frequent then.

**Comment by WtfJoke** [comment]
Since the errors are produced by ibm's cli, you should try to lookup on similar errors online.

Do you use scm/lscm?

It could be that (l)scm consumes too much memory or similar. But that are just guesses.

**Comment by areebrtc** [comment]
We are using rtc2git utility, not rtc2gitcli. 
I searched for these or similar errors but couldn't find a relative link. We are using scm. 
Also, can you tell me what is the recommended system configuration (CPU cores, size of RAM, other configs) to run rtc2git utility.

**Comment by areebrtc** [comment]
Can someone update on this ?

**Comment by WtfJoke** [comment]
Im not really sure what to suggest...
If these error come more frequently do you notice any bigger RAM usage by the scm process? What happens if you load the workspace by eclipse in that case? Could it be that your workspace is somehow out of sync?

You could also try to see if lscm works better. 
I would do a clone on the workspace after the errors are appearing more often and do various tests (switching to lscm, reload workspace, etc..) and check if its better or worse. 

There is no such as a recommended configuration (a normal dev machine with 8gb(+) ram should do the job). 

I usually used existingWorkspace=true, used lscm (for better performance, does not always suits, since deamon could also crash) and set encoding to utf8

Would be glad if you can report your findings for other users

**Comment by areebrtc** [comment]
It's not the SCM process but in top command I see two command as Java using 5.6 Gigs and 0.9 Gigs of RAM. My total ram size 48 GBs and eventually it gets used to almost 1 GB free when I run migration for almost 32000 change sets. 

I increased the stack size in scm.ini config file to 32 MB and the above error resolved but now I am facing new issue as below: -

12:15:26 - Set component '<component name >'(_sZBLwE4gEeKa7d7GLrHY3A) to baseline '<baseline name>' (_7YsscGC8EemGgo-8Bv58Xg)
12:15:40 - Set component '<component name>'(_eqJ5oA3vEeOhyfRzuEZ76A) to baseline '<baseline name>' (_hFsDsJHcEeiq17BEjkoR1g)Problem running 'set component':
Replace components failed.
Unable to delete <file path on git repo>/.project : Errors occurred while refreshing resources with the local file system.
Check the log for details about the error at "/root/.jazz-scm". If you have configured custom logging check your log configuration settings for the path to the log file.
Problem running 'load':
Exception during load
Unable to delete <file path on git repo>/.project : Errors occurred while refreshing resources with the local file system.
Check the log for details about the error at "/root/.jazz-scm". If you have configured custom logging check your log configuration settings for the path to the log file.
Switched to a new branch '<stream to be migrated as branch name>'
Components out of sync:
Workspace: (1000) "<my workspace name>"
  (1001) "<component name>"
Problem running 'accept':
Local file system is out of sync. Run 'scm load' with --force option to reload the workspace.
Problem running 'load':
Exception during load

How should proceed now? Please help.

**Comment by WtfJoke** [comment]
Wow, that memory consumption is huge. Did you tried to stop the java processes? And do you know which java processes (produced by which programm, probably still the scm)? 

If you experience this error it means that your local workspace is out of sync with the workspace state on the rtc server. 

As the error says you can reload the workspace by using scm load (with force). 
In that case, you probably have code changes which you could commit on your own. If you dont commit on your own, it will be commited with the next change.

**Comment by areebrtc** [comment]
Yes, there were two Java processes running as 
a. JazzTeamServer_6.0.2
b. Migration initiated java process due to scm execution

I have successfully resolved the above issue. Thanks for your support and response. 

Now, sometimes I see following error

# On branch CC-REL-6.0.0.2-Maint-Stream_branchpoint
nothing to commit, working directory clean
Root exception:
com.ibm.team.filesystem.client.FileSystemException: CRRTC5094E: The gap in the history is too large and contains too many change sets for a fill operation.
        at com.ibm.team.filesystem.cli.client.internal.subcommands.AcceptCmd.fetchGapFillingChangeSets(AcceptCmd.java:812)

Any idea on it ?

**Comment by WtfJoke** [comment]
> The gap in the history is too large and contains too many change sets for a fill operation.

Error pretty much says it all. You can try to load the workspace into eclipse and check if any conflicts occured, which stopped migration from proceeding. If so, you should solve it there and continue (or redo).

**Comment by areebrtc** [comment]
Yeah, that was the issue. Thanks for all your help and support. I am closing this ticket (issue).
