### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https://github.com/

### ISSUE THREAD

**Issue by abubakarmkarajagi** [WtfJoke/rtc2git#167]
When ran migration.py it gives me error saying incorrect syntax.

it connects to Gitub and asks me to login . After login getting below error. Could you please help on resolving this issue ?

Here is the error which I receied.

remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "C:\CC_GIT_migration\RTC_GIT\rtc2git\migration.py", line 173, in <module>
    migrate()
  File "C:\CC_GIT_migration\RTC_GIT\rtc2git\migration.py", line 65, in migrate
    initialize()
  File "C:\CC_GIT_migration\RTC_GIT\rtc2git\migration.py", line 28, in initialize
    git.initalize()
  File "C:\CC_GIT_migration\RTC_GIT\rtc2git\gitFunctions.py", line 51, in initalize
    self.createrepo()
  File "C:\CC_GIT_migration\RTC_GIT\rtc2git\gitFunctions.py", line 64, in createrepo
    os.chdir(self.clonedRepoName)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https://github.com/repository name

**Comment by ripudamann** [comment]
Hi, which version of python are you using? I do not even get to this point and I was wondering if I am using the correct python version.  I am using 3.8.10

**Comment by abubakarmkarajagi** [comment]
Hello ,

I am using 3.11.2 version of Python.

Regards,
Abubakar.M.K
From: ripudamann ***@***.***>
Sent: Wednesday, March 15, 2023 9:45 PM
To: rtcTo/rtc2git ***@***.***>
Cc: Karajagi, Abubakar ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [rtcTo/rtc2git] OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https://github.com/ (Issue #167)


Hi, which version of python are you using? I do not even get to this point and I was wondering if I am using the correct python version. I am using 3.8.10

**Comment by ripsingh-cg-fi** [comment]
Hi, Thanks for letting me know.

**Comment by abubakarmkarajagi** [comment]
Will you be able to help on this issue ?

Regards,
Abubakar.M.K
From: ripsingh-cg-fi ***@***.***>
Sent: Thursday, March 16, 2023 4:18 PM
To: rtcTo/rtc2git ***@***.***>
Cc: Karajagi, Abubakar ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [rtcTo/rtc2git] OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https://github.com/ (Issue #167)


Hi, Thanks for letting me know.

**Comment by ripudamann** [comment]
I cannot say for sure, but it could be that the target directory mentioned in the config.ini need to be corrected

Have you mentioned it like as specified in the config.ini.sample as below:

# Folder to be created - where migration will take place
Directory = \dir\targetDir

**Comment by abubakarmkarajagi** [comment]
Hello ,

I already gave the path ***@***.*** .
Could you please let me know what could be the issue ?

Regards,
Abubakar.M.K
From: ripudamann ***@***.***>
Sent: Saturday, March 18, 2023 5:55 PM
To: rtcTo/rtc2git ***@***.***>
Cc: Karajagi, Abubakar ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [rtcTo/rtc2git] OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https://github.com/ (Issue #167)


I cannot say for sure, but it could be that the target directory mentioned in the config.ini need to be corrected

Have you mentioned it like as specified in the config.ini.sample as below:

Folder to be created - where migration will take place

Directory = \dir\targetDir
